### ISSUE TITLE
Hello, comrade!

### ISSUE THREAD

**Issue by Davidliang11292** [Soviet-Linux/CCCP#52]
I am from China, what can I do for you?

**Comment by ilovethensa** [comment]
> I am from China, what can I do for you?
There isnt much discussion here, you should join our(joke not intended) [discord server](https://discord.gg/CpkN3kAm3t)

**Comment by Davidliang11292** [comment]
> > I am from China, what can I do for you?
> There isnt much discussion here, you should join our(joke not intended) [discord server](https://discord.gg/CpkN3kAm3t)
> 

Sorry, I can't use Discord

**Comment by AleksArt000** [comment]
We are currently working on making packages for the base system in the OUR repo, so there isn't much interesting stuff going on right now

**Comment by AleksArt000** [comment]
> Is there anything I can do? (Sorry, I don't know how to program yet)

We mainly need packages right now, If you know how to compile software from source, you can check out the example.ecmp in Soviet-Linux/OUR repo to see how programs are packaged for soviet, then start creating packages yourself, however we don't have good documentation yet, and most discussions happen on discord.
[WIP Documentation](https://ilovethensa.github.io/soviet-docs/)

@ilovethensa  anything else we can do right now?

**Comment by ilovethensa** [comment]
> > Is there anything I can do? (Sorry, I don't know how to program yet)
> 
> We mainly need packages right now, If you know how to compile software from source, you can check out the example.ecmp in Soviet-Linux/OUR repo to see how programs are packaged for soviet, then start creating packages yourself, however we don't have good documentation yet, and most discussions happen on discord. [WIP Documentation](https://ilovethensa.github.io/soviet-docs/)
> 
> @ilovethensa anything else we can do right now?

dont think so, the package manager is kinda done we only need packages rn

**Comment by AleksArt000** [comment]
There is now a matrix channel at sovietlinux:nope.chat, that might solve the issue
