### ISSUE TITLE
license it under CmPLv2

### ISSUE THREAD

**Issue by SylvKT** [Soviet-Linux/CCCP#6]
https://revteccom.tk/commonsoftware.html

**Comment by TheHolyTachanka** [comment]
GPL doesn't allow license change unless all contributors agree, and getting everyone to agree will not be easy

**Comment by PKD667** [comment]
We don't need to change the GPL , juste make a fork , there are plenty

**Comment by PKD667** [comment]
But I don't think it's a good idea , we should instead make our own Socialist Public License

**Comment by TheHolyTachanka** [comment]
SPL the best license

**Comment by JohnVictoryz** [comment]
srry but the license wont be changing any time soon

**Comment by SylvKT** [comment]
this should be closed as Not Planned
